name: lunar_calendar_converter
version: 1.0.0
author: Jihua Huang <huangjihua2010@gmail.com>
description: >-
  You can use this converter to convert calendar from one to another between lunar calendar and solar calendar. Like
  `Lunar lunar = Lunar(lunarYear: 2022, lunarMonth: 4, lunarDay: 1, isLeap: true);
   Solar solar = LunarSolarConverter.lunarToSolar(lunar);`
  or
  `Solar solar = Solar(solarYear: 2018, solarMonth: 8, solarDay: 22);
   Lunar lunar = LunarSolarConverter.solarToLunar(solar);`

  The `Lunar` class can come out Chinese text for a lunar calendar, like
  `Lunar lunar = Lunar(lunarYear: 2018, lunarMonth: 8, lunarDay: 22);
   print(lunar);`
  You will get "庚子年(2020)闰四月初一".
homepage: https://github.com/huuang/lunar_calendar_converter
environment:
  sdk: '>=1.0.0 <3.0.0'
