name: lunar_calendar_converter
version: 1.0.0
author: Jihua Huang <huangjihua2010@gmail.com>
description: Please read README.md
homepage: https://github.com/huuang/lunar_calendar_converter
environment:
  sdk: '>=1.0.0 <3.0.0'